name: 'AndroidLint report to checkstyle converter'
description: 'Convert AndroidLint report to checkstyle format'
author: 'Swisyn'

inputs:
  lint_xml_file:
    description: 'Path of Android Lint XML file'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'smartphone'
  color: 'green'
