name: 'build-test'
on: 
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List files
        run: |
          ls
        shell: bash

      - name: Check report
        uses: ./
        with:
          lint_xml_file: 'lint-results-release.xml'

      - name: Check empty report
        uses: ./
        with:
          lint_xml_file: 'lint-results-release-empty.xml'
